###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################

photocontainer-api-mysql:
  image: mysql:5.7
  container_name: photocontainer-api-mysql
  ports:
    - 32706:3306
  volumes:
    - ./.database:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=photocontainer
    - MYSQL_USER=photocontainer
    - MYSQL_PASSWORD=1234

photocontainer-api-webserver:
  image: phpdockerio/nginx:latest
  container_name: photocontainer-api-webserver
  volumes:
      - ..:/var/www/photocontainer-api
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "8081:80"
  links:
   - photocontainer-api-php-fpm

photocontainer-api-php-fpm:
  build: .
  dockerfile: php-fpm/Dockerfile
  container_name: photocontainer-api-php-fpm
  volumes:
    - ..:/var/www/photocontainer-api
    - ./php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini
  links:
    - photocontainer-api-mysql
